# Generated by Django 4.2.6 on 2023-10-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('case1', models.CharField(max_length=150)),
                ('case2', models.CharField(max_length=150)),
                ('case3', models.CharField(max_length=150)),
                ('case4', models.CharField(max_length=150)),
            ],
        ),
    ]
