# Generated by Django 4.2.6 on 2023-10-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_freeservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeservices',
            options={'verbose_name': 'бесплатные услуги', 'verbose_name_plural': 'бесплатные услуги'},
        ),
        migrations.RemoveField(
            model_name='freeservices',
            name='name',
        ),
    ]
