# Generated by Django 4.2.6 on 2023-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_siterequest_user_delete_task_siterequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='siterequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siterequest',
            name='site_name',
            field=models.CharField(default='defult', max_length=150),
            preserve_default=False,
        ),
    ]
